spring:
  application:
    name: users-manager
  profile:
    active: ${SPRING_BOOT_PROFILES:${spring-boot.run.profiles}}
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    hikari:
      pool-name: users-manager
      connection-timeout: 10000
      minimumIdle: 5
      maximumPoolSize: 10
      maxLifetime: 7200000
      connectionTestQuery: SELECT 1
      retryTimeout: 5000
  sql:
    init:
      mode: always
  jpa:
    show-sql: ${SHOW_SQL:false}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  server:
    port: ${PORT:8080}
    servlet:
      context-path: /users-manager
  management:
    endpoints:
      web:
        exposure:
          include: health
user-manager:
  JWT-SECRET: ${JWT-SECRET}
  APP-UID: ${APP-UID}