spring:
  application:
    name: users-manager-dev
  datasource:
    url: ***
    username: ***
    password: ***
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
server:
  port: 8081
  servlet:
    context-path: /users-manager
