SET TIME ZONE 'America/Argentina/Buenos_Aires';

-- Tabla APPLICATIONS
CREATE TABLE IF NOT EXISTS APPLICATIONS (
    APP_ID VARCHAR(255) PRIMARY KEY,
    APP_NAME VARCHAR(255) DEFAULT NULL
);

-- Tabla ROLES
CREATE TABLE IF NOT EXISTS ROLES (
    ROLE_ID INT PRIMARY KEY,
    ROLE_NAME VARCHAR(255) DEFAULT NULL,
    APP_ID VARCHAR(255) DEFAULT NULL,
    CONSTRAINT FK_ROLES_APPLICATIONS FOREIGN KEY (APP_ID) REFERENCES APPLICATIONS (APP_ID)
);

-- Tabla USERS
CREATE TABLE IF NOT EXISTS USERS (
    USER_ID SERIAL PRIMARY KEY,
    BIRTH_DATE DATE DEFAULT NULL,
    CREATION_DATE TIMESTAMP DEFAULT NULL,
    USER_EMAIL VARCHAR(255) UNIQUE,
    FIRST_NAME VARCHAR(255) DEFAULT NULL,
    LAST_UPDATED TIMESTAMP DEFAULT NULL,
    LAST_NAME VARCHAR(255) DEFAULT NULL,
    USER_HASH_PASSWORD VARCHAR(255) DEFAULT NULL,
    USER_NAME VARCHAR(255) UNIQUE,
    APP_ID VARCHAR(255) DEFAULT NULL,
    CONSTRAINT USERS_APPLICATIONS_FK FOREIGN KEY (APP_ID) REFERENCES APPLICATIONS (APP_ID)
);

-- Tabla USER_ROLES
CREATE TABLE IF NOT EXISTS USER_ROLES (
    USER_ID INT NOT NULL,
    ROLE_ID INT NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT FK_USER_ROLES_ROLES FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ROLE_ID),
    CONSTRAINT FK_USER_ROLES_USERS FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);

-- Tabla PERMISSIONS
CREATE TABLE IF NOT EXISTS PERMISSIONS (
    PERMISSION_ID INT PRIMARY KEY,
    PERMISSION_NAME VARCHAR(255) DEFAULT NULL,
    ROLE_ID INT DEFAULT NULL,
    CONSTRAINT FK_PERMISSIONS_ROLES FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ROLE_ID)
);


INSERT INTO APPLICATIONS (APP_ID, APP_NAME)
VALUES ('173d3ca6-b1f9-11ef-92ee-0242ac110002', 'USERS-MANAGER')
ON CONFLICT (APP_ID) DO NOTHING;

INSERT INTO USERS (BIRTH_DATE,CREATION_DATE,USER_EMAIL,FIRST_NAME,LAST_UPDATED,LAST_NAME,USER_HASH_PASSWORD,USER_NAME,APP_ID) 
VALUES('2001-06-18',NULL,'varelavargasleandro@outlook.com.ar','Leandro Gastón',NULL,'Varela Vargas','$2a$10$hpwJBCGqZog7HzjA.bVRoeWztU1x5I02wu/gFnRUMnr191gz/WfwC','lvarela','173d3ca6-b1f9-11ef-92ee-0242ac110002')
ON CONFLICT (USER_EMAIL) DO NOTHING;

INSERT INTO ROLES (ROLE_ID,ROLE_NAME,APP_ID) 
VALUES
    (1,'ROLE_USER','173d3ca6-b1f9-11ef-92ee-0242ac110002'),
    (2,'ROLE_ADMIN','173d3ca6-b1f9-11ef-92ee-0242ac110002')
ON CONFLICT (ROLE_ID) DO NOTHING;

INSERT INTO PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,ROLE_ID) 
VALUES
    (1, 'USER-ADMINISTRATOR', 2),
    (2, 'USER-READER', 1)
ON CONFLICT (PERMISSION_ID) DO NOTHING;

INSERT INTO USER_ROLES (USER_ID,ROLE_ID) 
VALUES
    (1,1),
    (1,2)
ON CONFLICT (USER_ID,ROLE_ID) DO NOTHING;